% This is the graphical user interface (GUI) for the ABC Vocoder. Vocoder
% parameters can be set within the GUI for an audio input determined by the
% user.
% 
% Sean R. Anderson -- sean.hearing@gmail.com -- 080622

function ABCVocoder

% Initialize GUI
hndl.StartFig = figure('name','Experimenter Interface',...
    'Visible','on','Units','normalized','Position',[0.05,0.05,0.9,0.85]); % Opens at given location on screen

% Initialize data structure
set(gcf, 'UserData', hndl);

% Store data structure
hndl = get(gcf, 'UserData');

% Store hard-coded colors for later use
hndl.colors.white=[1 1 1];
hndl.colors.gray=[0.9255 0.9137 0.8471];
hndl.colors.green=[0.5 1 0.25];
hndl.colors.blue=[0.5 0.5 1];
hndl.colors.red=[1 0.25 0.25];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Top section: File input and start
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

uicontrol('Style','text','String','ABC Vocoder', ...
    'FontWeight', 'bold', ...
    'FontSize',36,...
    'Units', 'normalized', 'Position',[0.175,0.85,0.7,0.1]);

% Vocode button
hndl.Fig.Vocode = uicontrol('Style', 'pushbutton', 'String', 'VOCODE', ...
    'FontWeight', 'bold', ...
    'FontSize', 24, ...
    'backgroundcolor',hndl.colors.green, ...
    'callback',@VocodeStimulus, ...
    'Units', 'normalized', 'Position',[0.05,0.75,0.15,0.2]);

% Sampling frequency
uicontrol('Style','text','String','Output Sampling Frequency (Hz)', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.05,0.55,0.15,0.05]);
hndl.Fig.fs = uicontrol('Style', 'edit', ...
    'String', '44100', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.05,0.6,0.15,0.05]);

% Instructions
uicontrol('Style','text',...
    'String',{'Instructions for use:', ...
        ' ', ...
        '1. Open an audio file.', ...
        '2. Set vocoder parameters to desired values', ...
        '3. Click "VOCODE."'},...
    'FontWeight', 'bold', ...
    'FontSize',18,...
    'Units', 'normalized', 'Position',[0.05,0.1,0.15,0.4]);

% Audio input
hndl.Fig.RawData = uicontrol('Style', 'pushbutton', 'String', 'Open Audio File', ...
    'FontWeight', 'bold', ...
    'FontSize', 14, ...
    'backgroundcolor',hndl.colors.blue, ...
    'callback',@OpenRawData, ...
    'enable','on', ...
    'Units', 'normalized', 'Position',[0.25,0.75,0.15,0.1]);
hndl.Fig.FilePath = uicontrol('Style', 'edit', ...
    'String', 'Glow.wav', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.4,0.75,0.4,0.1]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A: Audibility
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Style','text','String','A: Audibility (Hearing Loss in dB HL)', ...
    'FontWeight', 'bold', ...
    'FontSize',18,...
    'Units', 'normalized', 'Position',[0.225,0.65,0.6,0.05]);

uicontrol('Style','text','String','0.25 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.25,0.55,0.05,0.05]);
hndl.Fig.A250 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.25,0.6,0.05,0.05]);

uicontrol('Style','text','String','0.50 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.35,0.55,0.05,0.05]);
hndl.Fig.A500 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.35,0.6,0.05,0.05]);

uicontrol('Style','text','String','1.00 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.45,0.55,0.05,0.05]);
hndl.Fig.A1000 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.45,0.6,0.05,0.05]);

uicontrol('Style','text','String','2.00 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.55,0.55,0.05,0.05]);
hndl.Fig.A2000 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.55,0.6,0.05,0.05]);

uicontrol('Style','text','String','4.00 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.65,0.55,0.05,0.05]);
hndl.Fig.A4000 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.65,0.6,0.05,0.05]);

uicontrol('Style','text','String','8.00 kHz', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.75,0.55,0.05,0.05]);
hndl.Fig.A8000 = uicontrol('Style', 'edit', ...
    'String', '0', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.75,0.6,0.05,0.05]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% B: Broadness of tuning
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Style','text','String','B: Broadness of Tuning (i.e., Overlap Between Filters)', ...
    'FontWeight', 'bold', ...
    'FontSize',18,...
    'Units', 'normalized', 'Position',[0.225,0.45,0.6,0.05]);

uicontrol('Style','text','String','dB/ERB (Should be empty, zero, or neg)', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.425,0.35,0.2,0.05]);
hndl.Fig.B = uicontrol('Style', 'edit', ...
    'String', '', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.5,0.4,0.05,0.05]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% C: Compression
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
uicontrol('Style','text','String','C: Compression (i.e., Dynamic Range)', ...
    'FontWeight', 'bold', ...
    'FontSize',18,...
    'Units', 'normalized', 'Position',[0.225,0.25,0.6,0.05]);

uicontrol('Style','text','String','Percent (1 = No Compression; 0 = Full Compression)', ...
    'FontWeight', 'bold', ...
    'FontSize',14,...
    'Units', 'normalized', 'Position',[0.425,0.15,0.2,0.05]);
hndl.Fig.C = uicontrol('Style', 'edit', ...
    'String', '1', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'backgroundcolor',hndl.colors.white, ...
    'callback',@SetParams,...
    'Units', 'normalized', 'Position',[0.5,0.2,0.05,0.05]);


set(hndl.StartFig, 'UserData', hndl);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% SUB-FUNCTIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function OpenRawData(varargin)

    % Get data structure
    hndl = get(gcf, 'UserData');
    
    % Open UI to input file
    [filename,pathname] = uigetfile('*.*','Choose the audio file to vocode.',...
        'Multiselect','off');
    
    % Store filename and path
    pathname = sprintf('%s%s',pathname,filename);
    
    % Update filename in GUI
    set(hndl.Fig.FilePath,'String',pathname);
    
end


function SetParams(varargin)

    % Get data structure
    hndl = get(gcf, 'UserData');

    % Set each parameter in-line with vocoder
    hndl.freq = [250 500 1000 2000 4000 8000]';
    hndl.A = [str2double(get(hndl.Fig.A250,'String')) ...
        str2double(get(hndl.Fig.A500,'String')) ...
        str2double(get(hndl.Fig.A1000,'String')) ...
        str2double(get(hndl.Fig.A2000,'String')) ...
        str2double(get(hndl.Fig.A4000,'String')) ...
        str2double(get(hndl.Fig.A8000,'String'))]';
    hndl.audiogram = [hndl.freq hndl.A];
    hndl.B = str2double(get(hndl.Fig.B,'String'));
    if isnan(hndl.B)
        hndl.B = [];
    end
    hndl.C = str2double(get(hndl.Fig.C,'String'));
    hndl.fs = str2double(get(hndl.Fig.fs,'String'));
    hndl.pathname = get(hndl.Fig.FilePath,'String');

    % Update data structure
    set(gcf,'UserData',hndl);

end

function VocodeStimulus(varargin)
        
    % Set parameters for the vocoder
    SetParams;

    % Get data structure
    hndl = get(gcf, 'UserData');
    
    % Vocode stimulus
    vocoded_stim = Vocode(hndl.pathname,[250 10000],hndl.audiogram,hndl.B,hndl.C,hndl.fs);
    
    % Write out audio
    if ~isempty(hndl.B)
        audiowrite(sprintf('%s_%dMeanThreshold_%ddBperERBSpread_%0.2fDR.wav',...
            hndl.pathname, ...
            round(mean(hndl.A)),...
            round(hndl.B),...
            hndl.C), ... 
                vocoded_stim,...
                hndl.fs);
    else
        audiowrite(sprintf('%s_%dMeanThreshold_NoSpread_%0.2fDR.wav',...
            hndl.pathname, ...
            round(mean(hndl.A)),...
            hndl.C), ... 
                vocoded_stim,...
                hndl.fs);
    end
        
end
